### ISSUE TITLE
Greate work!

### ISSUE THREAD

**Issue by eduscrakozabrus** [SolidZORO/leaa#14]
Hello! This is a awesome project. And you profi! Please post documentation in english.

**Comment by SolidZORO** [comment]
The initial project was to write documentation and code comments in English, but I found that after I did not maintain the code, I came back to look at the code for a while, and I found that I could n’t understand them well because my English is not good , I have to convert those crappy English back to Chinese to understand its meaning, but this effect is very poor. So recently I started to comment in Chinese, after all, My native language is Chinese.

But I still insist on using git commit in English, I hope some key places in the future, I can write both Chinese and English.

----

最开始项目是用英文写文档和代码注释，但我发现，在我不维护代码后一段时间再回来看这些代码，我发现连我自己都不能很好理解它们了，因为我的英文并不好，我必须把之前那些蹩脚的英文转回中文去理解它的意思，不过这样效果很差。所以最近我开始用中文注释，毕竟我的母语是中文。

但 git commit 我还是会坚持用英文，希望以后某些关键的地方，我可以同时写上中文和英文。
